### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by herrniffler** [ChrisScheffler/ccrtble#1]
log:
> $ npm install ccrtble
> npm ERR! code ENOVERSIONS
> npm ERR! No valid versions available for ccrtble
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/pi/.npm/_logs/2020-11-20T08_29_44_288Z-debug.log

**Comment by ChrisScheffler** [comment]
As for now you have have to clone the GitHub-Repository as I did not publish it to npm yet.
